import { execSync } from "node:child_process";
import { copyFileSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import dotenv from "dotenv";
import { buildLocalResetCommand } from "../lib/db/migrate-commands";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SECRETS_FILE = resolve(ROOT, ".env.local.secrets");
const ENV_LOCAL = resolve(ROOT, ".env.local");
const REMOTE_BACKUP = resolve(ROOT, ".env.local.remote.bak");

const SUPABASE_ENV_KEYS = [
  "NEXT_PUBLIC_SUPABASE_URL",
  "NEXT_PUBLIC_SUPABASE_ANON_KEY",
  "SUPABASE_SERVICE_ROLE_KEY",
] as const;

const PRESERVE_KEYS = new Set([
  "LLM_PROVIDER",
  "LLM_BASE_URL",
  "LLM_MODEL",
  "LLM_API_KEY",
  "OPENAI_API_KEY",
  "DASHSCOPE_API_KEY",
  "ZHIPUAI_API_KEY",
  "MOONSHOT_API_KEY",
  "MINIMAX_API_KEY",
  "ANTHROPIC_API_KEY",
  "ANTHROPIC_MODEL",
  "REPORT_GENERATE_MAX_TOKENS",
]);

function dockerEnv(): NodeJS.ProcessEnv {
  const env = { ...process.env };
  delete env.DOCKER_HOST;
  return env;
}

function run(command: string): void {
  execSync(command, { cwd: ROOT, stdio: "inherit", env: dockerEnv() });
}

function capture(command: string): string {
  return execSync(command, { cwd: ROOT, encoding: "utf8", env: dockerEnv() }).trim();
}

function tryCapture(command: string): string | null {
  try {
    return capture(command);
  } catch {
    return null;
  }
}

function loadEnvFile(path: string): Record<string, string> {
  if (!existsSync(path)) {
    return {};
  }
  return dotenv.parse(readFileSync(path, "utf8"));
}

function shouldPreserve(key: string): boolean {
  return PRESERVE_KEYS.has(key);
}

function loadPreservedSecrets(): Record<string, string> {
  const preserved: Record<string, string> = {};

  for (const file of [SECRETS_FILE, ENV_LOCAL]) {
    for (const [key, value] of Object.entries(loadEnvFile(file))) {
      if (shouldPreserve(key) && value.trim()) {
        preserved[key] = value.trim();
      }
    }
  }

  return preserved;
}

function isRemoteSupabaseUrl(url: string): boolean {
  const trimmed = url.trim();
  if (!trimmed) {
    return false;
  }
  return !trimmed.includes("127.0.0.1") && !trimmed.includes("localhost");
}

function formatEnvValue(value: string): string {
  if (/[\s#"'\\]/.test(value)) {
    return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
  }
  return value;
}

function ensureDocker(): void {
  if (tryCapture("docker info") !== null) {
    return;
  }

  const hasColima = tryCapture("colima version") !== null;
  if (hasColima) {
    console.log("Docker unavailable — starting Colima...");
    run("colima start");
    tryCapture("docker context use colima");
    if (tryCapture("docker info") !== null) {
      return;
    }
  }

  throw new Error(
    hasColima
      ? "Colima failed to start Docker. Run `colima start` manually, then retry `npm run provision:local`."
      : "Docker is not running. Start Colima (`colima start`) or Docker Desktop, then retry `npm run provision:local`.",
  );
}

function backupRemoteEnvIfNeeded(): void {
  if (!existsSync(ENV_LOCAL)) {
    return;
  }

  const current = loadEnvFile(ENV_LOCAL);
  const supabaseUrl = current.NEXT_PUBLIC_SUPABASE_URL ?? "";
  if (!isRemoteSupabaseUrl(supabaseUrl)) {
    return;
  }

  copyFileSync(ENV_LOCAL, REMOTE_BACKUP);
  console.log("Backed up remote .env.local → .env.local.remote.bak");
}

function readLocalSupabaseEnv(): Record<string, string> {
  const output = capture(
    [
      "npx supabase status -o env",
      "--override-name api.url=NEXT_PUBLIC_SUPABASE_URL",
    ].join(" "),
  );

  const parsed = dotenv.parse(output);
  const mapped: Record<string, string> = {
    NEXT_PUBLIC_SUPABASE_URL:
      parsed.NEXT_PUBLIC_SUPABASE_URL?.trim() ?? parsed.API_URL?.trim() ?? "",
    NEXT_PUBLIC_SUPABASE_ANON_KEY:
      parsed.NEXT_PUBLIC_SUPABASE_ANON_KEY?.trim() ?? parsed.ANON_KEY?.trim() ?? "",
    SUPABASE_SERVICE_ROLE_KEY:
      parsed.SUPABASE_SERVICE_ROLE_KEY?.trim() ??
      parsed.SERVICE_ROLE_KEY?.trim() ??
      "",
  };

  const missing = SUPABASE_ENV_KEYS.filter((key) => !mapped[key]?.trim());
  if (missing.length > 0) {
    throw new Error(
      `Local Supabase status is missing: ${missing.join(", ")}. Run \`npx supabase start\` and retry.`,
    );
  }

  return mapped;
}

function writeLocalEnv(
  supabaseEnv: Record<string, string>,
  preserved: Record<string, string>,
): void {
  const lines = [
    "# Generated by npm run provision:local",
    "# Local Supabase stack — isolated from preview/production.",
    "# Restore remote credentials from .env.local.remote.bak if needed.",
    "",
    "# --- Supabase (local Docker) ---",
  ];

  for (const key of SUPABASE_ENV_KEYS) {
    lines.push(`${key}=${formatEnvValue(supabaseEnv[key] ?? "")}`);
  }

  lines.push("", "# --- LLM (from .env.local.secrets or previous .env.local) ---");
  if (Object.keys(preserved).length === 0) {
    lines.push(
      "# Add LLM_API_KEY to .env.local.secrets, then re-run provision:local",
    );
  } else {
    for (const [key, value] of Object.entries(preserved)) {
      lines.push(`${key}=${formatEnvValue(value)}`);
    }
  }

  lines.push(
    "",
    "# Passkeys: configured in supabase/config.toml ([auth.passkey] / [auth.webauthn]).",
    "# Long screenshots use in-process Playwright locally (E2B not configured).",
    "",
  );

  writeFileSync(ENV_LOCAL, `${lines.join("\n")}\n`, "utf8");
}

function verifyLocalPasskeysEnabled(): void {
  const body = tryCapture(
    'curl -s http://127.0.0.1:54321/auth/v1/passkeys',
  );
  if (!body) {
    console.warn("\nWarning: could not verify local passkey endpoint.");
    return;
  }
  if (body.includes("passkey_disabled")) {
    throw new Error(
      "Local Supabase passkeys are disabled. Check supabase/config.toml ([auth.passkey] enabled = true), then run: npx supabase stop && npx supabase start",
    );
  }
  console.log("Local passkey auth endpoint is enabled.");
}

function warnIfMissingLlmKey(preserved: Record<string, string>): void {
  const hasLlmKey = [
    "LLM_API_KEY",
    "OPENAI_API_KEY",
    "DASHSCOPE_API_KEY",
    "ZHIPUAI_API_KEY",
    "MOONSHOT_API_KEY",
    "MINIMAX_API_KEY",
    "ANTHROPIC_API_KEY",
  ].some((key) => preserved[key]?.trim());

  if (!hasLlmKey) {
    console.warn(
      "\nWarning: no LLM API key found. Copy .env.local.secrets.example → .env.local.secrets and add your key.",
    );
  }
}

function main(): void {
  console.log("Provisioning isolated local development environment...\n");

  ensureDocker();
  backupRemoteEnvIfNeeded();

  const preserved = loadPreservedSecrets();
  warnIfMissingLlmKey(preserved);

  console.log("Restarting local Supabase (Docker) to apply config.toml…");
  run("npx supabase stop");
  run("npx supabase start --exclude vector,analytics");
  verifyLocalPasskeysEnabled();

  console.log("\nApplying migrations (local reset — drops local data only)...");
  run(buildLocalResetCommand());

  const supabaseEnv = readLocalSupabaseEnv();
  writeLocalEnv(supabaseEnv, preserved);

  console.log("\nValidating .env.local...");
  run("npm run prepare:local");

  const studioUrl =
    dotenv.parse(capture("npx supabase status -o env")).STUDIO_URL ??
    "http://127.0.0.1:54323";

  console.log("\nLocal environment ready.");
  console.log("- App:             npm run dev  →  http://localhost:3000");
  console.log(`- Supabase Studio: ${studioUrl}`);
  console.log("- Stop Supabase:   npm run supabase:stop");
}

try {
  main();
} catch (err) {
  const message = err instanceof Error ? err.message : String(err);
  console.error(`\nProvision failed: ${message}`);
  process.exit(1);
}
